### DISCUSSION TITLE
Upgrading to latest release?

### DISCUSSION THREAD

**Discussion by bagelwoof** [garethgeorge/backrest#101] [Q&A] [answered]
Hello! This tool is awesome! Thank you!

Now that that's said, I have Backrest installed on a Pi using the installer script. How do I upgrade to the latest build? Should I just download the latest release and rerun the installer script?

**Comment by garethgeorge** [comment, marked as answer]
Hi, sorry I missed this for a few days. Yep! Rerunning the install.sh script is the intended upgrade path at the moment. It’s expected to safely stop, replace, and restart the currently running version.

**Comment by noelhibbard** [comment]
I just whipped up this script to update backrect on my Debian server if it helps:
```bash
#!/bin/bash

# Create temp folder
mkdir backrest-upgrade && cd backrest-upgrade

# Find and download the latest release (requires curl and jq)
curl -sL "$(curl -s https://api.github.com/repos/garethgeorge/backrest/releases | jq -r '.[0].assets[] | select(.name == "backrest_Linux_x86_64.tar.gz") | .browser_download_url')" -o backrest_Linux_x86_64.tar.gz

# Extract/Install
tar -xzvf backrest_Linux_x86_64.tar.gz
./install.sh

# Cleanup
cd ..
rm -r backrest-upgrade
```

I added some environment variables to my systemd service but I did this using an override (```systemctl edit backrest```) rather than editing the original service file, so there is no chance of my changes being wiped by install.sh.

**Reply by gturi** [reply]
I have modified a bit @noelhibbard script to not have to rely on `jq` to select the correct url since it is usually not preinstalled in linux distros:

```bash
#!/bin/bash

set -o errexit

cd "$(dirname "$0")" # cd to the directory of this script


# Create temp folder

updgrade_dir=backrest-upgrade
mkdir "$updgrade_dir" && cd "$updgrade_dir"


# Find and download the latest release

file_name="backrest_Linux_x86_64.tar.gz"

latest_release_info_url="https://api.github.com/repos/garethgeorge/backrest/releases/latest"
file_pattern="https://github.com/garethgeorge/backrest/releases/download/.*/$file_name"

file_archive_url="$(curl -s "$latest_release_info_url" | grep -o "$file_pattern")"

curl -sL "$file_archive_url" -o "$file_name"


# Extract/Install

tar -xzvf "$file_name"
./install.sh


# Cleanup

cd ..
rm -r "$updgrade_dir"
```

**Reply by DominikBritz** [reply]
I've created an Ansible playbook to install/update backrest.

```
- name: Ensure curl and jq are installed
  ansible.builtin.package:
    name:
      - curl
      - jq
    state: present

- name: Create a temporary folder for backrest upgrade
  ansible.builtin.file:
    path: /tmp/backrest-upgrade
    state: directory

- name: Find and download the latest backrest release
  ansible.builtin.shell:
    cmd: >
      curl -sL "$(curl -s https://api.github.com/repos/garethgeorge/backrest/releases | 
      jq -r '.[0].assets[] | select(.name == "backrest_Linux_x86_64.tar.gz") | .browser_download_url')" 
      -o /tmp/backrest-upgrade/backrest_Linux_x86_64.tar.gz
  args:
    chdir: /tmp/backrest-upgrade

- name: Extract the downloaded backrest package
  ansible.builtin.unarchive:
    src: /tmp/backrest-upgrade/backrest_Linux_x86_64.tar.gz
    dest: /tmp/backrest-upgrade
    remote_src: yes

- name: Run the installation script
  ansible.builtin.command:
    cmd: ./install.sh
    chdir: /tmp/backrest-upgrade

- name: Clean up the temporary folder
  ansible.builtin.file:
    path: /tmp/backrest-upgrade
    state: absent

- name: Ensure systemd override directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/backrest.service.d
    state: directory

- name: Listen on all interfaces
  ansible.builtin.copy:
    dest: /etc/systemd/system/backrest.service.d/override.conf
    content: |
      Environment="BACKREST_PORT=0.0.0.0:9898"

- name: Reload systemd daemon
  ansible.builtin.command:
    cmd: systemctl daemon-reload

- name: Restart backrest service
  ansible.builtin.service:
    name: backrest.service
    state: restarted
```
