### DISCUSSION TITLE
Is there a way to replace Host name?

### DISCUSSION THREAD

**Discussion by edersong** [garethgeorge/backrest#111] [Q&A] [answered]
Hello,
Is there a way to replace the Host name on Docker setting it the server's hostname that is running?
![image](https://github.com/garethgeorge/backrest/assets/64137913/19b1bc63-b224-4cdf-9f22-e9e4ccaac2dc)

**Comment by garethgeorge** [comment]
Hey, this isn't configurable in the UI at the moment (and is primarily cosmetic). You can configure this by editing the config.json and changing the "host" field (and then restarting backrest).

**Reply by edersong** [reply, marked as answer]
Thank you for the feedback.
Found a way to set it using the `hostname` option on docker. It's like the example below:

```
version: "3.2"
services:
  backrest:
    image: garethgeorge/backrest
    container_name: backrest 
    hostname: serverxyz
    volumes:
...
```
