### DISCUSSION TITLE
using environment variables for multiple repos

### DISCUSSION THREAD

**Discussion by schose** [garethgeorge/backrest#258] [General]
Hi all,

We are currently starting the backrest container and passing environment variables like AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, RESTIC_PASSWORD to the container. This helps us to setup the repo in config.json 

```json
  "repos":  [
    {
      "id":  "repo1",
      "uri":  "s3:https://s3-eu-central-1.amazonaws.com/myresticrepo1",
    }
```

. Now we would like to add more repos and tried to define the variables like AWS_SECRET_ACCESS_KEY for repo2 like this from a variable REPO2_AWS_ACCESS_KEY_ID:

```yaml
{
  "modno":  6,
  "version":  1,
  "host":  "resticrepo1",
  "repos":  [
    {
      "id":  "repo1",
      "uri":  "s3:https://s3-eu-central-1.amazonaws.com/myresticrepo1",
    },
    {
      "id":  "repo2",
      "uri":  "s3:https://s3-eu-central-1.amazonaws.com/myresticrepo2",
      "password":  "$REPO2_RESTIC_PASSWORD",
      "env":  [
        "AWS_ACCESS_KEY_ID=$REPO2_AWS_ACCESS_KEY_ID",
        "AWS_SECRET_ACCESS_KEY=$REPO2_AWS_SECRET_ACCESS_KEY"
      ],
      "prunePolicy":  {
        "maxFrequencyDays":  7,
        "maxUnusedPercent":  25
      }
    }
  ],
  "auth":  {
    "disabled":  true
  }
}
```

It seems that AWS_ACCESS_KEY_ID for repo2 is not using the env variable. Is there any way to archive that? 

Background: we prefer using env. variables as those are not printed out in the webgui. We have some users, who should be able to restore and authenticate on an apache reverse proxy before backrest UI. We do not want give away AWS_ACCESS_KEY_ID... but enable the user to restore from the UI. 

Our workaround would be to have one backrest instance per repo, but it would easier for the user to have all in one webgui.

Thanks and best regards,

Andreas
