### DISCUSSION TITLE
Docker resetting and losing backup info

### DISCUSSION THREAD

**Discussion by BrandonMillerSwingtech** [garethgeorge/backrest#267] [Q&A] [answered]
I am running Backrest in Docker on my Unraid server. I have got it working pretty well, except for one thing. Any time I go into the Docker settings and change a path or variable, Unraid re-downloads and resets the container. I have the BACKREST_CONFIG environmental variable pointing to my persistent config path so that when it resets I no longer lose the configuration of the repos and plans. However, if it resets, any previous snapshots do not show up under the repo. If I run stats it picks it up and shows it in the operation list, but it shows it as an unassociated backup. Is there a setting I'm missing to make sure the snapshots show up and are still associated like usual if the docker gets reset? Thank you.

**Comment by garethgeorge** [comment, marked as answer]
Hey, sounds like your environment variables (or mounts) are not setup correctly. Some portion of backrest's data is getting lost when the container restarts.

Make sure your config matches
```
services:
  backrest:
    image: garethgeorge/backrest
    container_name: backrest
    hostname: backrest #Use this to set the hostname instead of container ID to the config.json and WebUI.
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - /MY-BACKUP-DATA:/userdata # mount your directories to backup somewhere in the filesystem
      - /MY-REPOS:/repos # (optional) mount your restic repositories somewhere in the filesystem.
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
```

And in particular it sounds like the BACKREST_DATA directory is being lost. I recommend using the default value `/data/ ` for the environment variable and making sure that you map your path on the host to `/data` in the container.
