### DISCUSSION TITLE
Docker setup issues

### DISCUSSION THREAD

**Discussion by chief-lewus** [garethgeorge/backrest#381] [Q&A] [answered]
I've got the latest version of Backrest running inside docker. When I go to create a plan I cannot select the path I want to backup. It will show me most of the paths on the server but I'd like to backup /home/MYUSER/docker. If I manually type it in I get an error saying its not a file or directory as well. If I try to just select /home it will run the backup but there is nothing in it.

Not sure what I'm doing wrong here. Any help would be appreciated. I've attached my docker compose file as well.
```

services:
  backrest:
    image: garethgeorge/backrest:latest-alpine
    container_name: backrest
    hostname: backrest
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - /home/MYUSER/docker:/userdata # [optional] mount local paths to backup here.
      - /mnt/storinator/restic:/repos # [optional] mount repos if using local storage, not necessary for remotes e.g. B2, S3, etc.
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=America/Chicago # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    ports:
      - 9898:9898``
```
