### DISCUSSION TITLE
What about block devices?

### DISCUSSION THREAD

**Discussion by lakemike** [garethgeorge/backrest#750] [Q&A]
Is it possible to use restic / backrest also for backup of block devices?

I have this storage device in incus:
```
  ix_virt_zvol_root:
    boot.priority: "1"
    io.bus: nvme
    source: /dev/zvol/tank-SSD/vms/HAOS
    type: disk

```
Would it make sense to convert it to .img and then run restic / backrest? Would this allow to detect the differential changes?
