### DISCUSSION TITLE
Timezone not being observed

### DISCUSSION THREAD

**Discussion by mitchplze** [garethgeorge/backrest#753] [Q&A]
Hello. I've used backrest before, but I'm working on a new Docker deployment and cannot get the timezone to work at all. 

````
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: x
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - ./backrest/tmp:/tmp
      - /srv:/mnt/srv:ro  # Mount local paths to backup
      #- /path/to/local/repos:/repos     # Mount local repos (optional for remote storage)
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=America/Vancouver
    ports:
      - "9898:9898"
    restart: unless-stopped
````

No matter what, the backup times and all UI times are all in UTC. I have even tried mounting /etc/timezone to /etc/timezone:ro, with the same issue.

The host system clock is also in UTC, and is confirmed correct. 

Any ideas on how to get this working again or have I caught a new TZ bug?
