### DISCUSSION TITLE
Unable to Add Restic Repository

### DISCUSSION THREAD

**Discussion by xd003** [garethgeorge/backrest#769] [Q&A] [answered]
Hello
First of all, thank you for creating this project! I've never used any backup tool before, but I came across Backrest on Reddit where it was highly recommended for making Restic much more user-friendly. I'm currently trying to add my first Restic repository, but I'm running into an error.

For context, I'm running Backrest inside a Docker container. The repository I'm trying to use is a Google Drive remote configured with Rclone, which I have mounted into the container using Docker Compose.

However, when I fill in all the required details and click the "Submit" button, I encounter the following error:
![firefox_ItdpsoDLqe](https://github.com/user-attachments/assets/85a0e640-957d-43f3-a3f3-ea12b9cb3dd0)

Below is the Docker Compose file I'm using:
```
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - ./backrest/tmp:/tmp
      - /opt/docker/stacks:/userdata
      - ./rclone:/root/.config/rclone:ro 
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Asia/Kolkata
    expose:
      - 9898
    restart: unless-stopped
```
I'm encountering a write permission error in the `./rclone` directory on the host, which makes sense since the volume is mounted as read-only (:ro). However, I configured the volume this way based on your suggestion in [this comment](https://github.com/garethgeorge/backrest/discussions/766#discussioncomment-13010783).
