### ISSUE TITLE
Backrest not saving any data in docker

### ISSUE THREAD

**Issue by willyp713** [garethgeorge/backrest#113]
**Describe the bug**
This is probably a config issue, but Backrest isn't saving anything into my mounted volumes, like for `/config` or `/data`. The folders exist and are empty. Every time I re-compose the container, it's like all the settings are gone (users are gone, etc).

**To Reproduce**
Here is my compose file:
```
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest 
    restart: unless-stopped
    volumes:
      - ${BACKREST_DATA}:/data
      - ${BACKREST_CONFIG}:/config
      - ${XDG_CACHE_HOME}:/cache
      - ${USER_DATA}:/userdata:ro
    env_file:
      - .env
    ports:
      - 9898:9898
```

And in the `.env` file:
```
BACKREST_DATA=/mnt/user/appdata/backrest/data
BACKREST_CONFIG=/mnt/user/appdata/backrest/config
XDG_CACHE_HOME=/mnt/cache_nvme/restic_cache
USER_DATA=/mnt/user
```

**Expected behavior**
I expect the `/config` folder to have the appropriate json file and the `/data` directory to not be empty

**Desktop (please complete the following information):**
 - OS: docker on Unraid
 - Backrest 0.13.0

**Comment by garethgeorge** [comment]
Ah, this could perhaps be stated more explicitly in the docs. The default locations where backrest looks for config and stores data is oriented towards direct install on Linux (e.g. no containerization). When using the docker image, it's important to explicitly set the BACKREST_* environment variables to let backrest know where you're mounting it's storage. 

With your example, I think you want to modify your compose file to:

```
services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest 
    restart: unless-stopped
    volumes:
      - ${BACKREST_DATA}:/data
      - ${BACKREST_CONFIG}:/config
      - ${XDG_CACHE_HOME}:/cache
      - ${USER_DATA}:/userdata:ro
    env_file:
      - .env
    env:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
    ports:
      - 9898:9898
```
