### ISSUE TITLE
Command output is not valid JSON: unexpected end of JSON input

### ISSUE THREAD

**Issue by marcopaggioro** [garethgeorge/backrest#160]
**Describe the bug**
While executing a backup into local repository that error is reported:
```
error: forget: get snapshots for repo backups: command "/data/restic-0.16.4 forget --json -o sftp.args=-oBatchMode=yes --tag plan:everyday_backup --group-by tag" failed: command output is not valid JSON: unexpected end of JSON input
```

I'm running backrest in docker and I tryed `latest` and `latest-alpine` image
```
backrest:
    container_name: backrest
    image: garethgeorge/backrest
    hostname: alta
    volumes:
      - /home/marco/homeassistant/backrest/data:/data
      - /home/marco/homeassistant/backrest/config:/config
      - /home/marco/homeassistant/backrest/cache:/cache
      - /home/marco/homeassistant:/homeassistant:ro
      - /backups:/backups
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
    ports:
      - "8081:9898"
    restart: always
```

![image](https://github.com/garethgeorge/backrest/assets/24371500/c7349254-855d-45e2-a85d-500c33d31de3)
