### ISSUE TITLE
plan _system_ not found on v1.3.0

### ISSUE THREAD

**Issue by http-kennedy** [garethgeorge/backrest#383]
When running "Check Now" or "Prune" getting error message that _system_ not found.

**To Reproduce**
Repo Settings -> Prune Now or Check Now

**Screenshots**
![image](https://github.com/user-attachments/assets/edf0ccdf-e8e0-4a0a-8286-77152edc9d5b)
![image](https://github.com/user-attachments/assets/4459827f-cb8e-447a-af19-b8d6563241c5)

**Platform Info**
- Docker Container
- Backrest Version 1.3.0

**Additional context**
compose.yaml

```
version: "3.2"
services:
  backrest:
    image: garethgeorge/backrest
    container_name: backrest
    hostname: backrest
    volumes:
      - /root/.config/backrest/data:/data
      - /root/.config/backrest/config:/config
      - /root/.config/backrest/cache:/cache
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
    restart: unless-stopped
    ports:
      - 9898:9898
networks: {}
```
