### ISSUE TITLE
Add reverse proxy nginx configuration example

### ISSUE THREAD

**Issue by jibwf** [garethgeorge/backrest#594]
Note: if you have a question or want discussion please post in the [discussions area](https://github.com/garethgeorge/backrest/discussions).

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I am hitting issue when setup reverse proxy on nginx. I think it may related with Authorization header.

**Describe the solution you'd like**

Here is my exmaple fo reference, but I do not know if it is best. 

    location / {
      proxy_pass http://192.168.1.2:9898;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Port $server_port;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass_header Authorization;                                   >>>
      proxy_set_header Authorization $http_authorization;   >>>
    }
  }

**Additional context**

**Comment by garethgeorge** [comment]
Hi -- first, thanks for posting the example. Can you elaborate on the issues you were hitting? Are they resolved in that config or are you still working through a problem?

**Comment by jibwf** [comment]
> Hi -- first, thanks for posting the example. Can you elaborate on the issues you were hitting? Are they resolved in that config or are you still working through a problem?

After enabled reverse proxy by nginx, I was not able to login the backrest page. It routed to nginx admin page automaticlly.

Now, after add  both "proxy_pass_header Authorization" and "proxy_set_header Authorization", I can login to backrest successfully. 

But even add authorization header, I still see API reconnect warning sometimes.

**Comment by colserra1** [comment]
I am running into a similar issue: I am also running backrest behind nginx, and while I never had trouble reaching the login page, I do get the API Errors every few minutes. I already tried increasing the timeout interval without success. My nginx conf:

`server {
    listen 54.39.243.77:443 ssl;
    server_name X
    server_tokens off;
    ssl_certificate X
    ssl_certificate_key X;

    client_max_body_size 20M;
    location / {
        proxy_pass http://127.0.0.1:9898;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 1d;
        proxy_send_timeout 1d;
        keepalive_timeout 1d;
        proxy_intercept_errors on;
    }
}`

This also means that the progress indicators for operations are not working since the seesions does not get kept alive long enough.

**Comment by garethgeorge** [comment]
You might also try turning off `proxy_buffering off;` which should help with streaming compatibility. Generally, Backrest makes heavy use of HTTP streams. Keepalive timeout is also known to be important -- backrest will send an empty packet every 1 minute to try to help with this, but the timeout parameter must be at least a few minutes.

I'd encourage using a more modern reverse proxy e.g. Caddy for the best experience but I do believe some users have had success with nginx.

**Comment by sejoharp** [comment]
Hi. I managed to get it running with caddy. Maybe this help others.

Here is my docker compose file:
```yaml
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "9898:9898"
    volumes:
      - ./caddy/conf/:/etc/caddy/
      - ./caddy/data:/data
      - ./caddy/config:/config
    depends_on:
      - backrest
    restart: unless-stopped
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ./backrest/data:/data
      - /mnt/user/share:/backup:ro
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - ./backrest/tmp:/tmp
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Berlin
      - BACKREST_PORT=0.0.0.0:9999
    restart: unless-stopped
```

Here is my Caddyfile:
```shell
https://nas.internal:9898 {
	reverse_proxy backrest:9999 {
		header_up Host {host}
		header_up X-Real-IP {remote_host}
	}

	log {
		output discard # disables access logs
	}
}
```

I am not using nginx, but this config seems to work as well:
```shell
server {
    listen 9898 ssl;
    #    listen 443 ssl;
    #    openssl req -x509 -nodes   -newkey rsa:2048   -keyout nginx/server.key   -out nginx/server.crt   -subj "/CN=nginx-backrest"
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    access_log off;
    location / {
        proxy_pass http://backrest:9999;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

Full disclosure: I made heavy use of ChatGPT, so there might be parts that aren’t perfect. After getting the Nginx setup running, I asked ChatGPT to create a Caddyfile.
