### ISSUE TITLE
We need an healthcheck for backrest

### ISSUE THREAD

**Issue by francescor** [garethgeorge/backrest#767]
we are using backrest in docker (and docker swarm), we need some http health check on port 9898

something like  `0.0.0.0:9898/health`

**Comment by francescor** [comment]
We  already added the following


```
    healthcheck:
      test: [ "CMD", "curl", "--silent", "-f", "localhost:9898", " --output", "/tmp/anythinghere"  ]
      interval: 300s
      timeout: 5s
      retries: 5
```


and the curl return `0`, so it is ok, but from the aws load balancer we cannot add that `--output` on curl

**Comment by francescor** [comment]
this one is good, too


```
    healthcheck:
      test: [ "CMD", "wget", "--spider", "localhost:9898" ]
      interval: 60s
      timeout: 15s
      retries: 5
```


but there is no way I let the ELB to realize the service is up

I've tried many


```
http://localhost:9898/  200
http://localhost:9898/// 301
http://localhost:9898/anything 404
```

a plain basic `http://localhost:9898/something  => 200` would be great.

Any suggestion?   favicon? a logo?
